/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface Cliente {
  cli_abreviatura: string;
  cli_estado: Generated<number>;
  cli_id: Generated<number>;
  cli_nomaperazsocial: string;
  cli_numdocumento: string;
  tipdoc_id: number;
}

export interface Departamento {
  dep_id: Generated<number>;
  dep_nombre: string | null;
  pai_id: number | null;
}

export interface DetallePartidaGrupoPartida {
  detpargrupar_id: Generated<number>;
  grupar_id: number | null;
  par_id: number | null;
}

export interface DetallePartidaRecurso {
  detparrec_id: Generated<number>;
  detrec_precio: Numeric | null;
  par_id: number;
  rec_cantidad: Numeric | null;
  rec_cuadrilla: Numeric | null;
  rec_id: number;
}

export interface DetalleRolModulo {
  detrolmod_id: Generated<number>;
  mod_id: number;
  rol_id: number;
}

export interface Distrito {
  dist_id: Generated<number>;
  dist_nombre: string | null;
  prov_id: number | null;
}

export interface GrupoPartida {
  grupar_estado: Generated<number>;
  grupar_id: Generated<number>;
  grupar_nombre: string;
  grupar_total: Numeric | null;
  parent_id: number | null;
  pre_id: number;
}

export interface Modulo {
  mod_estado: Generated<number>;
  mod_id: Generated<number>;
  mod_nombre: string;
}

export interface Pais {
  pai_id: Generated<number>;
  pai_nombre: string | null;
}

export interface Partida {
  par_estado: Generated<number>;
  par_id: Generated<number>;
  par_nombre: string;
  par_preunitario: Numeric | null;
  par_renequipo: Numeric;
  par_renmanobra: Numeric;
  unimed_id: number;
}

export interface PrecioRecursoPresupuesto {
  pre_id: number;
  prp_id: Generated<number>;
  rec_id: number;
  rec_precio: Numeric | null;
}

export interface Presupuesto {
  cli_id: number;
  pre_codigo: string | null;
  pre_estado: Generated<number>;
  pre_fechorregistro: Generated<Timestamp>;
  pre_id: Generated<number>;
  pre_jornal: Numeric;
  pre_nombre: string;
  ubipre_id: number | null;
  usu_id: number;
}

export interface Provincia {
  dep_id: number | null;
  prov_id: Generated<number>;
  prov_nombre: string | null;
}

export interface Recurso {
  rec_estado: Generated<number>;
  rec_id: Generated<number>;
  rec_indunificado: string;
  rec_nombre: string;
  tiprec_id: number;
  unimed_id: number | null;
}

export interface Rol {
  rol_estado: Generated<number>;
  rol_id: Generated<number>;
  rol_nombre: string;
}

export interface TipoDocumento {
  tipdoc_id: Generated<number>;
  tipdoc_nombre: string;
}

export interface TipoRecurso {
  tiprec_id: Generated<number>;
  tiprec_nombre: string;
}

export interface UbicacionPresupuesto {
  dep_id: number | null;
  dist_id: number | null;
  pai_id: number | null;
  prov_id: number | null;
  ubipre_id: Generated<number>;
}

export interface UnidadMedida {
  unimed_abreviatura: string;
  unimed_estado: Generated<number>;
  unimed_id: Generated<number>;
  unimed_nombre: string;
}

export interface Usuario {
  rol_id: number;
  usu_clave: string;
  usu_correo: string;
  usu_estado: Generated<number>;
  usu_fechoraregistro: Generated<Timestamp>;
  usu_fechoratokenactualizado: Timestamp | null;
  usu_id: Generated<number>;
  usu_nomapellidos: string;
  usu_observacion: string | null;
  usu_tokenactualizado: string | null;
}

export interface DB {
  cliente: Cliente;
  departamento: Departamento;
  detalle_partida_grupo_partida: DetallePartidaGrupoPartida;
  detalle_partida_recurso: DetallePartidaRecurso;
  detalle_rol_modulo: DetalleRolModulo;
  distrito: Distrito;
  grupo_partida: GrupoPartida;
  modulo: Modulo;
  pais: Pais;
  partida: Partida;
  precio_recurso_presupuesto: PrecioRecursoPresupuesto;
  presupuesto: Presupuesto;
  provincia: Provincia;
  recurso: Recurso;
  rol: Rol;
  tipo_documento: TipoDocumento;
  tipo_recurso: TipoRecurso;
  ubicacion_presupuesto: UbicacionPresupuesto;
  unidad_medida: UnidadMedida;
  usuario: Usuario;
}
